server:
  port: 9090
spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/user_master
    username: postgres
    password: root
  jpa:  
    hibernate:
      ddl-auto: validate
    show-sql: true
management:
  endpoints:
    web:
      exposure:
         include: refresh