server:
  port: 8089

spring:
  application:
    name: gateway-service

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: dev

  main:
    web-application-type: reactive

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  cloud:
    gateway:
      routes:
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - name: ApiFilter

        - id: customer-service-route
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
          filters:
            - name: ApiFilter

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: ApiFilter

        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - name: ApiFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
