spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
         include: refresh
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
